version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    #restart: always
    ports: 
      - 51993:1972
      - 52993:52773
      - 53993
    volumes:
      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app